substitutions:
  name: "haos-cyd-controller-prod"
  friendly_name: "CYD Prod"
  device_description: "Homeassistant Dashboard on CYD Production Device"

packages:
  base: !include source/base.yaml
  env: !include source/env-prod.yaml
  device: !include source/ESP32-8048S.yaml
  display: !include source/ESP32-8048S050-display.yaml
